function recomendacion(texto) {
    const lib = [
        { titulo: "Don quijote de la mancha", autor: "Miguel de Cervantes" },
        { titulo: "En busca del tiempo perdido", autor: "Marcel Proust" },
        { titulo: "Odisea", autor: "Homero" },
        { titulo: "El proceso", autor: "Franz Kafka" },
        { titulo: "La metamorfosis", autor: "Franz Kafka" },
        { titulo: "Ana kerenina", autor: "León Tolstói" },
        { titulo: "Moby dick", autor: "Herman Melville" },
        { titulo: "cuentos", autor: "Antón Chéjov" },
        { titulo: "Guerra y paz", autor: "León Tolstói" },
        { titulo: "ficciones", autor: "Jorge Luis Borges" },
        { titulo: "Poeta en nueva york", autor: "Federico García Lorca" },
        { titulo: "Los hermanos karamazov", autor: "Fiódor Dostoievski" },
        { titulo: "Crimen y castigo", autor: "Fiódor Dostoievski" },
        { titulo: "La biblia", autor: "Alguien" },
        { titulo: "La montaña magica", autor: "Thomas Mann" },
        { titulo: "Pedro paramo", autor: "Juan Ruflo" },
        { titulo: "Ulises", autor: "James Joyce" },
        { titulo: "El ruido y la furia", autor: "William Faulkner" },
        { titulo: "Madame bovary", autor: "Gustave Flaubert" },
        { titulo: "Las mil y una noches", autor: "Alguien" },
        { titulo: "Bajo el volcan", autor: "Malcolm Lowry" },
        { titulo: "La muerte de virgilio", autor: "Hermann Broch" },
        { titulo: "Ensayos", autor: "Michel de Montaigne" },
        { titulo: "Lolita", autor: "Vladimir Nabokov" },
        { titulo: "Rojo y negro", autor: "Stendhal" },
        { titulo: "El aleph", autor: "Jorge Luis Borges" },
        { titulo: "Tristam shandy", autor: "Laurence Sterne" },
        { titulo: "El corazon es un cazador solitario", autor: "Carson McCullers" },
        { titulo: "El corazon de las tinieblas", autor: "Joseph Conrad" },
        { titulo: "Las flores del mal", autor: "Charles Baudelaire" },
        { titulo: "El banquete", autor: "Platón" },
        { titulo: "El guardian entren el centeno", autor: "JD Salinger" },
        { titulo: "La educacion sentimental", autor: "Gustave Flaubert" },
        { titulo: "Elegias de duino", autor: "Rainer Maria Rilker" },
        { titulo: "Rimas y leyendas", autor: "Gustavo Adolfo Bequer" },
        { titulo: "El oficio de vivir", autor: "Cesare Pavese" },
        { titulo: "El libro de desasosiego", autor: "Fernando Pessoa" },
        { titulo: "Obra completa", autor: "Jorge Luis Borges" },
        { titulo: "Asi hablo zaratustra", autor: "Friederich Nietzsche" },
        { titulo: "La isla del tesoro", autor: "Robert Louis Stevenson" },
        { titulo: "Rayuela", autor: "Julio Cortázar" },
        { titulo: "Fortuna y jacinta", autor: "Benito Pérez Galdós" },
        { titulo: "Historias extraordinarias", autor: "Edgar Allan Poe" },
        { titulo: "La cuidad y los perros", autor: "Mario Vargas Llosa" },
        { titulo: "La tierra baldia", autor: "TS Elilot" },
        { titulo: "Metamorfosis", autor: "Ovidio" },
        { titulo: "Poemas", autor: "Emily Dickinson" },
        { titulo: "El rey lear", autor: "William Shakespeare" },
        { titulo: "Hamlet", autor: "William Shakespeare" },
        { titulo: "Trilce", autor: "César Vallejo" },
        { titulo: "El extranjero", autor: "Albert Camus" },
        { titulo: "Absalon", autor: "ABSALÓN", autor: "William Faulkner" },
        { titulo: "Odas", autor: "Horacio" },
        { titulo: "El largo adios", autor: "Raymond Chandler" },
        { titulo: "El idiota", autor: "Fiódor Dostoievski" },
        { titulo: "El astillero", autor: "Juan Carlos Onetti" },
        { titulo: "El primer hombre", autor: "Albert Camus" },
        { titulo: "El hacedor", autor: "Jorge Luis Borges" },
        { titulo: "Cien años de soledad", autor: "Gabriel García Márquez" },
        { titulo: "La divina comedia", autor: "Dante Alighieri" },
        { titulo: "La regenta", autor: "Leopoldo Alas Clarín" },
        { titulo: "Las olas", autor: "Virginia Woolf" },
        { titulo: "Mientras agonizo", autor: "William Faulkner" },
        { titulo: "Diarios", autor: "Franz Kafka" },
        { titulo: "La celestina", autor: "Fernando de Rojas" },
        { titulo: "Ricardo III", autor: "William Shakespeare" },
        { titulo: "Residencia de la tierra", autor: "Pablo Neruda" },
        { titulo: "Demian", autor: "Herman Hesse" },
        { titulo: "Dr jekyll y mr hyde", autor: "Robert Louis Stevenson" },
        { titulo: "Conversacion en el catedral", autor: "Mario Vargas Llosa" },
        { titulo: "Orgullo y prejuicio", autor: "Jane Austen" },
        { titulo: "El gatopardo", autor: "Giussepe Tomasi di Lampedusa" },
        { titulo: "Lord jim", autor: "Joseph Conrad" },
        { titulo: "Lazarillo de tormes", autor: "Anónimo" },
        { titulo: "Viaje al fin de la noche", autor: "Louis Ferdinand Céline" },
        { titulo: "Canto general", autor: "Pablo Neruda" },
        { titulo: "Iliada", autor: "Homero" },
        { titulo: "Luces de bohemia", autor: "Ramón María del Valle-Inclán" },
        { titulo: "La guerra del fin del mundo", autor: "Mario Vargas Llosa" },
        { titulo: "Alicia en el pais de las maravillas", autor: "Lewis Carroll" },
        { titulo: "Aforismos", autor: "GC Lichtenberg" },
        { titulo: "Manifesto comunista", autor: "Karl Marx" },
        { titulo: "Mortal y rosa", autor: "Francisco Umbral" },
        { titulo: "Dublineses", autor: "James Joyce" },
        { titulo: "El gran gatsby", autor: "F Scott Fitzgerald" },
        { titulo: "Peter pan", autor: "James Matthew Barrie" },
        { titulo: "Sonetos", autor: "Quevedo" },
        { titulo: "La tia julia y el escribidor", autor: "Mario Vargas Llosa" },
        { titulo: "David copperfield", autor: "Charles Dickens" },
        { titulo: "El cuarteto de alejandria", autor: "Lawrence Durrell" },
        { titulo: "La caida", autor: "Albert Camus" },
        { titulo: "Orlando", autor: "Virginia Woolf" },
        { titulo: "Los inconsolables", autor: "Kazuo Ishiguro" },
        { titulo: "Espacio", autor: "Juan Ramón Jiménez" },
        { titulo: "El maestro y margarita", autor: "Mijaíl Bulgakov" },
        { titulo: "El jardin de los finzi contini", autor: "Giorgio Bassani" },
        { titulo: "Palmetas salvajes", autor: "William Faulkner" },
        { titulo: "Harri eta herri", autor: "Gabriel Ares{ti" },
        { titulo: "Obras completas", autor: "Pío Baroja" },
        { titulo: "El segundo sexo", autor: "Simone de Beauvoir" }
    ];

    try {
        if (typeof(texto) === 'string') {
            console.log('La variable debe ser tipo string');
            return;
        }
        let result = lib.filter(item => {
            return (item.titulo.toLowerCase().includes(texto.toLowerCase()) ||
                item.autor.toLowerCase().includes(texto.toLowerCase()))
        });
        console.log(result);

    } catch (error) {
        console.log(error);
    }
}
let texto = 1
recomendacion(texto);